language: python
python:
- '2.7'
sudo: false
cache:
  directories:
  - "~/.platformio"
install:
- pip install -U platformio
script:
- platformio run
deploy:
  provider: releases
  api_key:
    secure: Wcvw+tvaddGWXPZungQNSO8bxMg3ejr23gd4wSXzTv1NIVzqUNRYdCBOvaXBBrH83bdt1Dm39Q9L5krVX7YC+iGL/o2ervUryt/lNu04uw8NIm0E6l5xFH8troSr92wz3KHjtpRSQxerM2XzZNTnt9J6KEKTkkjJvb3jOCwhUTCys/sQTKWl7ok96F+vWPXrGJD9n7RWNy6o/wL8aictu988AUl0L7uDcyULacgNmwNbGhUzk3GoMD6V0s/MFP+dEQjFqNIOan/7IBDnpmvpEYn4ZPjUEK11eW8j/5DhyCT73nh8Lv/+Rb+TNhIZJNiZNBsHyZHbPGm9Ziq93XsInfWBK3vLJnT4Ii2+sRhqasZnIohpw5t8dv33keGvhdEvwTla0nyl1bglUTVkhdZyb8NS+HzBvbzKGssRXTJSm2XacMpyYD+QgOcQ6irQv1nVOYyPnCCxm9fqCM4wtgaZt32amPb8nPAtXhVKwQ2gymCRbNUX9jjUEefKIPeGpEW+oBeWmFemODKyRMuWF5DnjPeZ83BwQkmMl5h3UjSs5MSzv0WQkKsltv8ZXvYLlp0JWAqTV7bQZS2PWa5bJRqfYIe8BsGr/J5HxbNTq0QbnVbwWth3VGDxJcfItgF0drcw3y8KQB/fr0CbfntrsPZ/EYPOi4uJz5PbH/LcFrDQ2uM=
  file: ".pioenvs/esp12e/firmware.bin"
  skip_cleanup: true
  on:
    repo: psy0rz/ESPEasy-platformio
notifications:
  email: false
